"use client";
import Link from "next/link";
import { useAppPreferences } from "@/components/app-providers";
import { DashboardHeader } from "@/components/dashboard-header";

type Props={cinema:{id:string;name:string;status:string;rejection_reason:string|null};navLabels:{staff:string;movies:string;screens:string;showtimes:string}};
const icons={staff:"◉",movies:"▶",screens:"▦",showtimes:"◷"};
export function CinemaDashboardView({cinema,navLabels}:Props){const{locale}=useAppPreferences();const ar=locale==="ar";const t=ar?{eyebrow:"لوحة السينما",status:"حالة المراجعة",pending:"السينما بانتظار مراجعة إدارة المنصة.",approved:"السينما معتمدة وجاهزة للإدارة.",suspended:"هذه السينما موقوفة حاليًا.",rejected:"سبب الرفض",overview:"مساحة الإدارة",overviewNote:"اختر القسم الذي تريد العمل عليه.",back:"العودة إلى دور السينما",manage:"إدارة",staff:"الطاقم",movies:"الأفلام",screens:"القاعات",showtimes:"مواعيد العرض"}:{eyebrow:"Cinema dashboard",status:"Review status",pending:"This cinema is waiting for platform review.",approved:"This cinema is approved and ready to manage.",suspended:"This cinema is currently suspended.",rejected:"Rejection reason",overview:"Management space",overviewNote:"Choose the area you want to work on.",back:"Back to your cinemas",manage:"Manage",staff:"Staff",movies:"Movies",screens:"Screens",showtimes:"Showtimes"};
 const statusLabel=cinema.status==="pending_review"?(ar?"قيد المراجعة":"Pending review"):cinema.status==="approved"?(ar?"معتمدة":"Approved"):cinema.status==="suspended"?(ar?"موقوفة":"Suspended"):(ar?"مرفوضة":"Rejected");
 const message=cinema.status==="pending_review"?t.pending:cinema.status==="approved"?t.approved:cinema.status==="suspended"?t.suspended:null;
 return <div className="dashboard-page"><DashboardHeader backHref="/dashboard"/><main className="dashboard-main"><section className="cinema-hero"><div className="cinema-avatar xl">{cinema.name.charAt(0)}</div><div className="cinema-hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{cinema.name}</h1><div className="cinema-status-line"><span>{t.status}</span><span className={`status-badge status-${cinema.status}`}>{statusLabel}</span></div></div></section>
 {(message||cinema.rejection_reason)&&<div className={`notice notice-${cinema.status}`} role={cinema.status==="rejected"||cinema.status==="suspended"?"alert":undefined}><strong>{statusLabel}</strong><span>{message}{cinema.rejection_reason&&`${t.rejected}: ${cinema.rejection_reason}`}</span></div>}
 <section className="dashboard-section"><div className="section-heading"><div><h2>{t.overview}</h2><p>{t.overviewNote}</p></div></div><nav className="management-grid" aria-label="Cinema management">{(["staff","movies","screens","showtimes"] as const).map(key=>{const manages=navLabels[key].startsWith("Manage");return <Link className="management-card" href={`/dashboard/${cinema.id}/${key}`} key={key}><span className="management-icon">{icons[key]}</span><div><h3>{manages?`${t.manage} ${t[key]}`:t[key]}</h3><p>{ar?"عرض التفاصيل والإعدادات":"View details and settings"}</p></div><span className="management-arrow">→</span></Link>})}</nav></section><Link className="back-link" href="/dashboard">← {t.back}</Link></main></div>}
